### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by nlp-wh** [dhwajraj/NER-RNN#6]
Traceback (most recent call last):
  File "C:/Users/weihao/Desktop/NER-RNN-master/NerMulti.py", line 213, in <module>
    X_train, y_train = get_input(BASE_DIR+"/eng.train")
  File "C:/Users/weihao/Desktop/NER-RNN-master/NerMulti.py", line 145, in get_input
    return np.asarray(sentence), sentence_tag
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\numpy\core\numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError

how to change？

**Comment by ChengTsang** [comment]
I want to ask the same question!

**Comment by alirezapir** [comment]
same problem...
